name              'motd-tail'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description 'Updates motd.tail with Chef Roles'
version           '5.1.0'
source_url        'https://github.com/sous-chefs/motd-tail'
issues_url        'https://github.com/sous-chefs/motd-tail/issues'
chef_version      '>= 12.15'

supports 'ubuntu'
